book_link: "https://www.railstutorial.org/book"
help_page_link: "https://www.railstutorial.org/help"
contact_link: "https://www.railstutorial.org/contact"
tutorial_link: "https://www.railstutorial.org/"
learn_enough_link: "https://www.learnenough.com/"
screencast_link: "https://screencasts.railstutorial.org/"
rails_link: "https://rubyonrails.org/"
news_railstutorial_link: "https://news.railstutorial.org/"
michaelhartl_link: "https://www.michaelhartl.com/"
gravatar_url: "https://secure.gravatar.com/avatar/"

rails_logo_width: "200"

MAX_LENGTH_USERNAME: 50
MAX_LENGTH_EMAIL: 255
MIN_LENGTH_PASSWORD: 6

DEFAULT_SIZE_GRAVATAR: 80

remember_me_enabled: "1"
