book_link: "https://www.railstutorial.org/book"
help_page_link: "https://www.railstutorial.org/help"
contact_link: "https://www.railstutorial.org/contact"
tutorial_link: "https://www.railstutorial.org/"
learn_enough_link: "https://www.learnenough.com/"
screencast_link: "https://screencasts.railstutorial.org/"
rails_link: "https://rubyonrails.org/"
news_railstutorial_link: "https://news.railstutorial.org/"
michaelhartl_link: "https://www.michaelhartl.com/"
gravatar_avatar_url: "https://secure.gravatar.com/avatar/"
gravatar_emails_url: "https://gravatar.com/emails"
server_email: "sonhh2003@gmail.com"

rails_logo_width: "200"

MAX_LENGTH_USERNAME: 50
MAX_LENGTH_EMAIL: 255
MIN_LENGTH_PASSWORD: 6

DEFAULT_SIZE_GRAVATAR: 80

remember_me_enabled: "1"

gravatar_size_50: 50
items_per_page_20: 20

minimum_pages_for_pagination_1_page: 1
PASSWORD_RESET_EXPIRATION_2: 2
MAX_LENGTH_MICROPOST_CONTENT_140: 140
IMAGE_RESIZE_TO_LIMIT_500_500: [500, 500]
IMAGE_SIZE_LARGE_LIMIT_5: 5
ACCEPTED_FORMAT_IMAGE: "image/jpeg,image/gif,image/png"
